version: '3.7'
services:
  agent:
    init: true
    container_name: ethstats
    image: xdaichain/ethstats-agent:latest
    links:
      - "node"
    depends_on:
      - "node"
    environment:
      NODE_ENV: production
      RPC_HOST: node
      RPC_PORT: 8545
      LISTENING_PORT: 30303
      CONTACT_DETAILS: "https://t.me/PolisPayOfficial"
      INSTANCE_NAME: ${ETHSTATS_ID}
      WS_SERVER: "wss://dev-netstats.polis.tech/api"
      WS_SECRET: ${ETHSTATS_KEY}
      VERBOSITY: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/openethereum:main
    user: root
    command:
      --chain=olympus
      --base-path=/root/data
      --min-gas-price="1000000000"
      --gas-floor-target="20000000"
      --gas-cap="1000000000"
      --author="0x276f658ddbfd910e27800ea0232e733e138ac478"
      --engine-signer="0x276f658ddbfd910e27800ea0232e733e138ac478"
      --unlock="0x276f658ddbfd910e27800ea0232e733e138ac478"
      --password="/root/password/0x276f658ddbfd910e27800ea0232e733e138ac478"
      --force-sealing
      --pruning=archive
      --max-peers="100"
      --jsonrpc-port="8545"
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --fat-db="on"
      --tracing="on"
      --ws-port="8546"
      --ws-interface all
      --ws-apis=all
      --ws-origins all
      --ws-hosts all
      --logging="engine=trace,miner=trace,rpc=info"
    volumes:
      - ./node_data:/root/data
      - ./passwords:/root/password
      - ./keys:/root/data/keys/olympus
    ports:
      - "8546:8546"
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always